# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build
on:
  push:
    paths: 
      - '**.js'
jobs:
  build:
    name : my job
    runs-on: ${{matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [10, 12, 14]
        
    steps:
    - uses: actions/checkout@v2
    - name: use node.js ${{matrix.node}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node}}
    - run: npm ci
    - run: npm run build --if-present
     
          
      
    
     

  
